### ISSUE TITLE
Status card generating error.

### ISSUE THREAD

**Issue by jylin34** [KnlnKS/leetcode-stats#14]
![image](https://github.com/KnlnKS/leetcode-stats/assets/45725145/25fcbf4e-ac03-4e66-96bd-a9b7d20b7afd)
There might be some changes on leetcode website.

**Comment by willyfh** [comment]
Seems LeetCode has employed bot protection, see here: https://github.com/JacobLinCool/LeetCode-Stats-Card/commit/4578bdacfc79361f69d4124bb24a8c684ee7737f

**Comment by KnlnKS** [comment]
It works now. So I shall close the issue.
